<!DOCTYPE html>

<html lang="fr">
<head>

  <meta charset="utf-8"/>

  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0" />

  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-touch-fullscreen" content="yes"/>

  <!-- build:style-->
  <?php echo self::loadStyle();?>
  <!-- endbuild -->

  <title>sample page</title>

</head>

<body>
  <div class="ligne">
    <div id="top" class="grid-12">
      <?php echo self::section('top');?><!-- appel des modules correspondant à cette section -->
    </div>
  </div>

  <div class="zone" id="content">
    <div class="ligne" id="content-header">
      <?php echo self::section('header');?><!-- appel des modules correspondant à cette section -->
    </div>

    <div class="ligne" id="content-middle">
      <?php echo self::section('middle');?><!-- appel des modules correspondant à cette section -->

    </div>

    <div class="ligne" id="content-bottom">
      <?php echo self::section('bottom');?><!-- appel des modules correspondant à cette section -->
    </div>

  </div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <!-- build:script-->
  <?php echo self::loadScript();?>
  <!-- endbuild -->
</body>
</html>